from __future__ import annotations

import json
import hashlib
from dataclasses import dataclass
from pathlib import Path

from symboliclight.ast import (
    App,
    AssertStmt,
    BinaryExpr,
    CallExpr,
    Expr,
    FunctionDecl,
    IfStmt,
    LetStmt,
    ListExpr,
    LiteralExpr,
    Module,
    PathExpr,
    RecordExpr,
    ReturnStmt,
    RouteDecl,
    Stmt,
    TypeDecl,
    TypeRef,
)


@dataclass(slots=True)
class GeneratedPython:
    code: str
    source_map: dict[str, object]


def generate_python(app: App) -> str:
    return generate_python_artifact(app).code


def generate_python_artifact(app: App, *, generated_path: str = "<generated>") -> GeneratedPython:
    if not isinstance(app, App):
        raise TypeError("Only app files can be compiled to Python.")
    generator = PythonGenerator(app)
    return generator.generate(generated_path=generated_path)


def generate_schema_hash(app: App) -> str:
    if not isinstance(app, App):
        raise TypeError("Only app files have generated schema hashes.")
    return PythonGenerator(app).schema_hash()


@dataclass(slots=True)
class PythonGenerator:
    app: App
    current_module_path: tuple[str, ...] = ()
    current_module: Module | None = None

    def generate(self, *, generated_path: str = "<generated>") -> GeneratedPython:
        lines: list[str] = [
            "# Generated by SymbolicLight. Do not edit by hand.",
            "from __future__ import annotations",
            "",
            "import argparse",
            "import datetime as _sl_datetime",
            "import json",
            "import os",
            "import sqlite3",
            "import sys",
            "import traceback",
            "import uuid as _sl_uuid",
            "from http.server import BaseHTTPRequestHandler, HTTPServer",
            "",
            "SL_LINE_MAP = {}",
            "SL_SCHEMA_VERSION = 1",
            f"SL_SCHEMA_HASH = {self.schema_hash()!r}",
            "SL_HTTP_MAX_BODY_BYTES = 1_000_000",
            "",
            "def sl_report_exception():",
            "    _, _, tb = sys.exc_info()",
            "    frames = traceback.extract_tb(tb) if tb else []",
            "    for frame in reversed(frames):",
            "        source = SL_LINE_MAP.get(frame.lineno)",
            "        if source:",
            "            print(f\"SL source: {source['file']}:{source['line']}:{source['column']}\", file=sys.stderr)",
            "            return",
            "",
            "def sl_error(code, message):",
            "    return {'error': {'code': code, 'message': message}}",
            "",
            "def sl_db_execute(action, sql, params=()):",
            "    try:",
            "        return conn().execute(sql, params)",
            "    except Exception as exc:",
            "        raise RuntimeError(f'database {action} failed: {exc}') from exc",
            "",
            "def sl_db_commit(action):",
            "    try:",
            "        conn().commit()",
            "    except Exception as exc:",
            "        raise RuntimeError(f'database {action} commit failed: {exc}') from exc",
            "",
            "def sl_validate_file_path(path):",
            "    if not isinstance(path, str) or not path:",
            "        raise RuntimeError('file path must be a non-empty Text value')",
            "    if os.path.isdir(path):",
            "        raise RuntimeError(f'file path points to a directory: {path}')",
            "    return path",
            "",
            "CONN = None",
            f"SL_DB_BACKEND = {self.app_backend()!r}",
            "",
            "def connect(db_path=None):",
            "    global CONN",
            "    if SL_DB_BACKEND == 'postgres':",
            "        try:",
            "            import psycopg",
            "            from psycopg.rows import dict_row",
            "        except ImportError as exc:",
            "            raise RuntimeError('Postgres apps require installing symboliclight[postgres].') from exc",
            "        url = db_path or os.environ.get('SL_DB_URL')",
            "        if not url:",
            "            raise RuntimeError('Postgres apps require SL_DB_URL or an explicit db path/url.')",
            "        CONN = psycopg.connect(url, row_factory=dict_row)",
            "    else:",
            "        path = db_path or os.environ.get('SL_DB', 'symboliclight.sqlite')",
            "        CONN = sqlite3.connect(path)",
            "        CONN.row_factory = sqlite3.Row",
            "    init_db()",
            "    return CONN",
            "",
            "def conn():",
            "    return CONN or connect()",
            "",
            "def json_ready(value):",
            "    return value",
            "",
            "def print_json(value):",
            "    print(json.dumps(json_ready(value), ensure_ascii=False, indent=2))",
            "",
            "def response(status, body, headers=None):",
            "    return {'__sl_response__': True, 'status': status, 'headers': headers or {}, 'body': body}",
            "",
            "def response_ok(status, body, headers=None):",
            "    return response(status, ok(body), headers)",
            "",
            "def response_err(status, code, message, headers=None):",
            "    return response(status, err({'code': code, 'message': message}), headers)",
            "",
            "def env(name, default):",
            "    return os.environ.get(name, default)",
            "",
            "def env_int(name, default):",
            "    try:",
            "        return int(os.environ.get(name, default))",
            "    except ValueError:",
            "        return default",
            "",
            "def uuid():",
            "    return str(_sl_uuid.uuid4())",
            "",
            "def now():",
            "    return _sl_datetime.datetime.now(_sl_datetime.UTC).isoformat()",
            "",
            "def read_text(path):",
            "    path = sl_validate_file_path(path)",
            "    try:",
            "        with open(path, 'r', encoding='utf-8') as handle:",
            "            return handle.read()",
            "    except OSError as exc:",
            "        raise RuntimeError(f'read_text failed for {path}: {exc}') from exc",
            "",
            "def write_text(path, content):",
            "    path = sl_validate_file_path(path)",
            "    try:",
            "        with open(path, 'w', encoding='utf-8') as handle:",
            "            handle.write(content)",
            "        return True",
            "    except OSError as exc:",
            "        raise RuntimeError(f'write_text failed for {path}: {exc}') from exc",
            "",
            "def some(value):",
            "    return value",
            "",
            "def none():",
            "    return None",
            "",
            "def ok(value):",
            "    return {'ok': value}",
            "",
            "def err(value):",
            "    return {'err': value}",
            "",
        ]
        lines.extend(self.emit_configs())
        lines.extend(self.emit_init_db())
        lines.extend(self.emit_fixtures())
        lines.extend(self.emit_imported_functions())
        for function in self.app.functions:
            lines.extend(self.emit_function(function))
        for route in self.app.routes:
            lines.extend(self.emit_route(route))
        lines.extend(self.emit_server())
        lines.extend(self.emit_tests())
        lines.extend(self.emit_main())
        code = "\n".join(lines) + "\n"
        source_map = build_source_map(code, generated_path=generated_path)
        compact_line_map = {
            int(line): location for line, location in source_map["line_map"].items()
        }
        code = code.replace("SL_LINE_MAP = {}", f"SL_LINE_MAP = {compact_line_map!r}", 1)
        source_map = build_source_map(code, generated_path=generated_path)
        return GeneratedPython(code, source_map)

    def emit_init_db(self) -> list[str]:
        lines = ["def init_db():", "    database = conn()"]
        placeholder = self.sql_placeholder()
        lines.extend([
            "    database.execute('CREATE TABLE IF NOT EXISTS sl_migrations (version INTEGER PRIMARY KEY, schema_hash TEXT NOT NULL)')",
            f"    row = database.execute('SELECT schema_hash FROM sl_migrations WHERE version = {placeholder}', [SL_SCHEMA_VERSION]).fetchone()",
            "    if row is None:",
            f"        database.execute('INSERT INTO sl_migrations (version, schema_hash) VALUES ({placeholder}, {placeholder})', [SL_SCHEMA_VERSION, SL_SCHEMA_HASH])",
            "    elif row['schema_hash'] != SL_SCHEMA_HASH:",
            "        print('warning: SymbolicLight schema drift detected; automatic migrations are not implemented', file=sys.stderr)",
        ])
        if not self.app.stores:
            lines.extend(["    database.commit()", "    return"])
        for store in self.app.stores:
            type_decl = self.type_decl(store.type_ref.name)
            columns = []
            for field in type_decl.fields:
                if field.name == "id":
                    id_type = "INTEGER PRIMARY KEY AUTOINCREMENT" if store.backend == "sqlite" else "BIGSERIAL PRIMARY KEY"
                    columns.append(f"{self.sql_identifier(field.name)} {id_type}")
                else:
                    columns.append(f"{self.sql_identifier(field.name)} {self.sql_type(field.type_ref, backend=store.backend)}")
            sql = f"CREATE TABLE IF NOT EXISTS {self.sql_identifier(store.name)} ({', '.join(columns)})"
            lines.append(f"    database.execute({sql!r})")
        lines.extend(["    database.commit()", ""])
        for store in self.app.stores:
            lines.extend(self.emit_store_helpers(store.name, self.type_decl(store.type_ref.name), backend=store.backend))
        return lines

    def emit_configs(self) -> list[str]:
        lines: list[str] = []
        for config in self.app.configs:
            lines.append(f"{config.name} = {{")
            for field in config.fields:
                lines.append(f"    {field.name!r}: {self.expr(field.default)},")
            lines.append("}")
            lines.append("")
        return lines

    def emit_store_helpers(self, store_name: str, type_decl: TypeDecl, *, backend: str) -> list[str]:
        data_fields = [field for field in type_decl.fields if field.name != "id"]
        table = self.sql_identifier(store_name)
        id_column = self.sql_identifier("id")
        placeholder = self.sql_placeholder(backend)
        columns = ", ".join(self.sql_identifier(field.name) for field in data_fields)
        placeholders = ", ".join(placeholder for _ in data_fields)
        values = ", ".join(f"item.get({field.name!r})" for field in data_fields)
        updates = ", ".join(f"{self.sql_identifier(field.name)} = {placeholder}" for field in data_fields)
        filter_columns = {
            field.name: self.sql_identifier(field.name)
            for field in type_decl.fields
        }
        lines = [
            f"def {store_name}_normalize(item):",
            "    item = dict(item)",
        ]
        bool_fields = [field.name for field in type_decl.fields if field.type_ref.name == "Bool"]
        if bool_fields:
            for field_name in bool_fields:
                lines.append(f"    if {field_name!r} in item:")
                lines.append(f"        item[{field_name!r}] = bool(item[{field_name!r}])")
        lines.extend(
            [
                "    return item",
                "",
            ]
        )
        lines.extend([
            f"def {store_name}_insert(item):",
            *self.emit_insert_lines(store_name, table, columns, placeholders, values, backend=backend),
            "",
            f"def {store_name}_all():",
            f"    rows = sl_db_execute('{store_name}.all', 'SELECT * FROM {table} ORDER BY {id_column}').fetchall()",
            f"    return [{store_name}_normalize(dict(row)) for row in rows]",
            "",
            f"def {store_name}_get(item_id):",
            f"    row = sl_db_execute('{store_name}.get', 'SELECT * FROM {table} WHERE {id_column} = {placeholder}', [item_id]).fetchone()",
            f"    return {store_name}_normalize(dict(row)) if row else None",
            "",
            f"def {store_name}_update(item_id, item):",
            "    item = dict(item)",
            f"    cursor = sl_db_execute('{store_name}.update', 'UPDATE {table} SET {updates} WHERE {id_column} = {placeholder}', [{values}, item_id])",
            "    if cursor.rowcount == 0:",
            f"        raise KeyError(f'{store_name}.update id not found: {{item_id}}')",
            f"    sl_db_commit('{store_name}.update')",
            f"    return {store_name}_get(item_id)",
            "",
            f"def {store_name}_try_update(item_id, item):",
            "    item = dict(item)",
            f"    cursor = sl_db_execute('{store_name}.try_update', 'UPDATE {table} SET {updates} WHERE {id_column} = {placeholder}', [{values}, item_id])",
            f"    sl_db_commit('{store_name}.try_update')",
            "    if cursor.rowcount == 0:",
            "        return None",
            f"    return {store_name}_get(item_id)",
            "",
            f"def {store_name}_delete(item_id):",
            f"    cursor = sl_db_execute('{store_name}.delete', 'DELETE FROM {table} WHERE {id_column} = {placeholder}', [item_id])",
            f"    sl_db_commit('{store_name}.delete')",
            "    return cursor.rowcount > 0",
            "",
            f"def {store_name}_filter(**criteria):",
            f"    allowed = {sorted(field.name for field in type_decl.fields)!r}",
            f"    columns = {filter_columns!r}",
            "    for key in criteria:",
            "        if key not in allowed:",
            "            raise ValueError(f'unknown filter field: {key}')",
            "    if not criteria:",
            f"        return {store_name}_all()",
            f"    where = ' AND '.join(f'{{columns[key]}} = {placeholder}' for key in criteria)",
            f"    rows = sl_db_execute('{store_name}.filter', 'SELECT * FROM {table} WHERE ' + where + ' ORDER BY {id_column}', list(criteria.values())).fetchall()",
            f"    return [{store_name}_normalize(dict(row)) for row in rows]",
            "",
            f"def {store_name}_count():",
            f"    row = sl_db_execute('{store_name}.count', 'SELECT COUNT(*) AS count FROM {table}').fetchone()",
            "    return int(row['count'])",
            "",
            f"def {store_name}_exists(item_id):",
            f"    row = sl_db_execute('{store_name}.exists', 'SELECT 1 FROM {table} WHERE {id_column} = {placeholder}', [item_id]).fetchone()",
            "    return row is not None",
            "",
            f"def {store_name}_clear():",
            f"    cursor = sl_db_execute('{store_name}.clear', 'DELETE FROM {table}')",
            f"    sl_db_commit('{store_name}.clear')",
            "    return cursor.rowcount",
            "",
        ])
        return lines

    def emit_insert_lines(
        self,
        store_name: str,
        table: str,
        columns: str,
        placeholders: str,
        values: str,
        *,
        backend: str,
    ) -> list[str]:
        if backend == "postgres":
            return [
                f"    cursor = sl_db_execute('{store_name}.insert', 'INSERT INTO {table} ({columns}) VALUES ({placeholders}) RETURNING {self.sql_identifier('id')}', [{values}])",
                "    row = cursor.fetchone()",
                f"    sl_db_commit('{store_name}.insert')",
                f"    return {store_name}_get(row['id'])",
            ]
        return [
            f"    cursor = sl_db_execute('{store_name}.insert', 'INSERT INTO {table} ({columns}) VALUES ({placeholders})', [{values}])",
            f"    sl_db_commit('{store_name}.insert')",
            f"    return {store_name}_get(cursor.lastrowid)",
        ]

    def emit_fixtures(self) -> list[str]:
        lines = ["def load_fixtures():"]
        if not self.app.fixtures:
            lines.append("    return")
            lines.append("")
            return lines
        for fixture in self.app.fixtures:
            for record in fixture.records:
                lines.append(f"    {fixture.store_name}_insert({self.expr(record)})")
        lines.append("")
        return lines

    def emit_imported_functions(self) -> list[str]:
        lines: list[str] = []
        for alias, module in self.app.imported_modules.items():
            lines.extend(self.emit_module_functions((alias,), module))
        return lines

    def emit_module_functions(self, module_path: tuple[str, ...], module: Module) -> list[str]:
        lines: list[str] = []
        for alias, imported in module.imported_modules.items():
            lines.extend(self.emit_module_functions((*module_path, alias), imported))
        for function in module.functions:
            lines.extend(self.emit_function(function, module_path=module_path, module=module))
        return lines

    def emit_function(
        self,
        function: FunctionDecl,
        *,
        module_path: tuple[str, ...] = (),
        module: Module | None = None,
    ) -> list[str]:
        name = self.python_function_name(function, module_path=module_path)
        params = ", ".join(param.name for param in function.params)
        lines = [self.source_comment(function.location), f"def {name}({params}):"]
        previous_module_path = self.current_module_path
        previous_module = self.current_module
        self.current_module_path = module_path
        self.current_module = module
        lines.extend(self.emit_body(function.body, indent="    "))
        self.current_module_path = previous_module_path
        self.current_module = previous_module
        if not function.body:
            lines.append("    pass")
        lines.append("")
        return lines

    def emit_route(self, route: RouteDecl) -> list[str]:
        lines = [self.source_comment(route.location), f"def {route.function_name}(request):"]
        lines.extend(self.emit_body(route.body, indent="    "))
        lines.append("")
        return lines

    def emit_body(self, statements: list[Stmt], *, indent: str, return_target: str | None = None) -> list[str]:
        lines: list[str] = []
        for stmt in statements:
            if isinstance(stmt, LetStmt):
                lines.append(f"{indent}{stmt.name} = {self.expr(stmt.expr)}")
            elif isinstance(stmt, ReturnStmt):
                if return_target is None:
                    lines.append(f"{indent}return {self.expr(stmt.expr)}")
                else:
                    lines.append(f"{indent}{return_target} = {self.expr(stmt.expr)}")
            elif isinstance(stmt, AssertStmt):
                lines.append(f"{indent}assert {self.expr(stmt.expr)}")
            elif isinstance(stmt, IfStmt):
                lines.append(f"{indent}if {self.expr(stmt.condition)}:")
                lines.extend(
                    self.emit_body(stmt.then_body, indent=indent + "    ", return_target=return_target)
                    or [indent + "    pass"]
                )
                if stmt.else_body:
                    lines.append(f"{indent}else:")
                    lines.extend(self.emit_body(stmt.else_body, indent=indent + "    ", return_target=return_target))
            else:
                lines.append(f"{indent}{self.expr(stmt.expr)}")
        return lines

    def emit_server(self) -> list[str]:
        route_entries = []
        body_entries = []
        for route in self.app.routes:
            route_entries.append(f"    ({route.method!r}, {route.path!r}): {route.function_name},")
            body_entries.append(f"    ({route.method!r}, {route.path!r}): {self.required_body_fields(route)!r},")
        return [
            "ROUTES = {",
            *route_entries,
            "}",
            "ROUTE_BODY_FIELDS = {",
            *body_entries,
            "}",
            "",
            "class Request:",
            "    def __init__(self, body=None, headers=None):",
            "        self.body = body or {}",
            "        self.headers = headers",
            "",
            "    def header(self, name):",
            "        if self.headers is None:",
            "            return None",
            "        return self.headers.get(name)",
            "",
            "class Handler(BaseHTTPRequestHandler):",
            "    def do_GET(self):",
            "        self.handle_method('GET')",
            "",
            "    def do_POST(self):",
            "        self.handle_method('POST')",
            "",
            "    def do_PUT(self):",
            "        self.handle_method('PUT')",
            "",
            "    def do_PATCH(self):",
            "        self.handle_method('PATCH')",
            "",
            "    def do_DELETE(self):",
            "        self.handle_method('DELETE')",
            "",
            "    def do_HEAD(self):",
            "        self.send_json(405, sl_error('method_not_allowed', 'Unsupported HTTP method.'))",
            "",
            "    def do_OPTIONS(self):",
            "        self.send_json(405, sl_error('method_not_allowed', 'Unsupported HTTP method.'))",
            "",
            "    def send_error(self, code, message=None, explain=None):",
            "        if code == 501:",
            "            self.send_json(405, sl_error('method_not_allowed', 'Unsupported HTTP method.'))",
            "            return",
            "        self.send_json(code, sl_error('http_error', message or 'HTTP error.'))",
            "",
            "    def handle_method(self, method):",
            "        handler = ROUTES.get((method, self.path))",
            "        if handler is None:",
            "            self.send_json(404, sl_error('not_found', f'No route for {method} {self.path}.'))",
            "            return",
            "        try:",
            "            length = int(self.headers.get('Content-Length', '0'))",
            "        except ValueError:",
            "            self.send_json(400, sl_error('bad_request', 'Content-Length must be an integer.'))",
            "            return",
            "        if length > SL_HTTP_MAX_BODY_BYTES:",
            "            self.send_json(413, sl_error('payload_too_large', 'Request body exceeds the 1000000 byte limit.'))",
            "            return",
            "        try:",
            "            raw = self.rfile.read(length).decode('utf-8') if length else '{}'",
            "        except UnicodeDecodeError:",
            "            self.send_json(400, sl_error('bad_request', 'Request body must be valid UTF-8.'))",
            "            return",
            "        try:",
            "            body = json.loads(raw or '{}')",
            "        except json.JSONDecodeError:",
            "            self.send_json(400, sl_error('bad_request', 'Request body must be valid JSON.'))",
            "            return",
            "        if not isinstance(body, dict):",
            "            self.send_json(400, sl_error('bad_request', 'Request body must be a JSON object.'))",
            "            return",
            "        required = ROUTE_BODY_FIELDS.get((method, self.path), [])",
            "        missing = [field for field in required if field not in body or body[field] is None]",
            "        if missing:",
            "            fields = ', '.join(missing)",
            "            self.send_json(400, sl_error('bad_request', f'Missing required body field(s): {fields}.'))",
            "            return",
            "        try:",
            "            result = handler(Request(body, self.headers))",
            "        except Exception:",
            "            sl_report_exception()",
            "            traceback.print_exc(file=sys.stderr)",
            "            self.send_json(500, sl_error('internal_error', 'Internal server error.'))",
            "            return",
            "        if isinstance(result, dict) and result.get('__sl_response__'):",
            "            self.send_json(result.get('status', 200), result.get('body'), result.get('headers', {}))",
            "            return",
            "        self.send_json(200, result)",
            "",
            "    def send_json(self, status, value, headers=None):",
            "        payload = json.dumps(value, ensure_ascii=False).encode('utf-8')",
            "        self.send_response(status)",
            "        for key, header_value in (headers or {}).items():",
            "            self.send_header(key, header_value)",
            "        self.send_header('Content-Type', 'application/json; charset=utf-8')",
            "        self.send_header('Content-Length', str(len(payload)))",
            "        self.end_headers()",
            "        self.wfile.write(payload)",
            "",
            "def serve(host='127.0.0.1', port=8000):",
            "    connect()",
            "    server = HTTPServer((host, port), Handler)",
            "    print(f'SymbolicLight app serving on http://{host}:{port}')",
            "    server.serve_forever()",
            "",
        ]

    def emit_tests(self) -> list[str]:
        lines = [
            "def assert_golden(value, expected_path):",
            "    actual = json.dumps(json_ready(value), ensure_ascii=False, indent=2, sort_keys=True).strip()",
            "    actual_path = expected_path + '.actual'",
            "    try:",
            "        with open(expected_path, 'r', encoding='utf-8') as handle:",
            "            expected = handle.read().strip()",
            "    except FileNotFoundError:",
            "        with open(actual_path, 'w', encoding='utf-8') as handle:",
            "            handle.write(actual + '\\n')",
            "        raise AssertionError(f'golden file not found: {expected_path}; actual written to {actual_path}')",
            "    if actual != expected:",
            "        with open(actual_path, 'w', encoding='utf-8') as handle:",
            "            handle.write(actual + '\\n')",
            "        raise AssertionError(f'golden mismatch: expected {expected_path}, actual {actual_path}')",
            "",
            "def run_tests():",
        ]
        if not self.app.tests:
            lines.append("    print('No tests defined.')")
            return lines + [""]
        executable_tests = 0
        for test in self.app.tests:
            lines.append(f"    {self.source_comment(test.location).lstrip()}")
            if test.external_ref is not None:
                lines.append(f"    print('skipped external test: {test.external_ref}')")
                continue
            executable_tests += 1
            lines.append(f"    # {test.name}")
            lines.append("    try:")
            lines.append("        connect(':memory:')")
            lines.append("        load_fixtures()")
            lines.append("        __sl_test_value = None")
            lines.extend(self.emit_body(test.body, indent="        ", return_target="__sl_test_value"))
            if test.golden_path is not None:
                lines.append(f"        assert_golden(__sl_test_value, {self.resolve_source_path(test.location.path, test.golden_path)!r})")
            lines.append("    except Exception:")
            lines.append("        sl_report_exception()")
            lines.append("        raise")
        lines.append(f"    print('ok - {executable_tests} test(s) passed')")
        lines.append("")
        return lines

    def emit_main(self) -> list[str]:
        lines = [
            "def main(argv=None):",
            "    parser = argparse.ArgumentParser(prog='sl-app')",
            "    sub = parser.add_subparsers(dest='command', required=True)",
            "    serve_parser = sub.add_parser('serve')",
            "    serve_parser.add_argument('--host', default='127.0.0.1')",
            "    serve_parser.add_argument('--port', type=int, default=8000)",
            "    sub.add_parser('test')",
        ]
        for function in self.app.functions:
            if function.kind != "command":
                continue
            lines.append(f"    {function.name}_parser = sub.add_parser({function.name!r})")
            for param in function.params:
                if param.type_ref.name == "Bool":
                    lines.append(f"    {function.name}_parser.add_argument('--{param.name}', action='store_true')")
                elif param.type_ref.name in {"Int", "Id"}:
                    lines.append(f"    {function.name}_parser.add_argument({param.name!r}, type=int)")
                elif param.type_ref.name == "Float":
                    lines.append(f"    {function.name}_parser.add_argument({param.name!r}, type=float)")
                else:
                    lines.append(f"    {function.name}_parser.add_argument({param.name!r})")
        lines.extend(
            [
                "    args = parser.parse_args(argv)",
                "    if args.command == 'serve':",
                "        serve(args.host, args.port)",
                "        return",
                "    if args.command == 'test':",
                "        run_tests()",
                "        return",
                "    connect()",
            ]
        )
        for function in self.app.functions:
            if function.kind != "command":
                continue
            params = ", ".join(f"args.{param.name}" for param in function.params)
            lines.extend(
                [
                    f"    if args.command == {function.name!r}:",
                    f"        print_json({self.python_function_name(function)}({params}))",
                    "        return",
                ]
            )
        lines.extend([
            "",
            "if __name__ == '__main__':",
            "    try:",
            "        main()",
            "    except Exception:",
            "        sl_report_exception()",
            "        raise",
            "",
        ])
        return lines

    def expr(self, expr: Expr) -> str:
        if isinstance(expr, LiteralExpr):
            return repr(expr.value)
        if isinstance(expr, PathExpr):
            return self.path_expr(expr.parts)
        if isinstance(expr, RecordExpr):
            fields = ", ".join(f"{field.name!r}: {self.expr(field.expr)}" for field in expr.fields)
            return "{" + fields + "}"
        if isinstance(expr, ListExpr):
            return "[" + ", ".join(self.expr(item) for item in expr.items) + "]"
        if isinstance(expr, BinaryExpr):
            op = {"&&": "and", "||": "or"}.get(expr.op, expr.op)
            return f"({self.expr(expr.left)} {op} {self.expr(expr.right)})"
        if isinstance(expr, CallExpr):
            return self.call_expr(expr)
        raise TypeError(f"Unsupported expression: {expr!r}")

    def path_expr(self, parts: list[str]) -> str:
        enum_literal = self.enum_variant_literal(parts)
        if enum_literal is not None:
            return enum_literal
        if parts[:2] == ["request", "body"] and len(parts) == 3:
            return f"request.body.get({parts[2]!r})"
        if len(parts) == 2:
            return f"{parts[0]}.get({parts[1]!r})"
        return parts[0]

    def call_expr(self, expr: CallExpr) -> str:
        if expr.callee == ["request", "header"]:
            args = ", ".join(self.arg_expr(arg) for arg in expr.args)
            return f"request.header({args})"
        if len(expr.callee) == 2 and expr.callee[0] in {store.name for store in self.app.stores}:
            store, method = expr.callee
            args = ", ".join(self.arg_expr(arg) for arg in expr.args)
            return f"{store}_{method}({args})"
        resolved_module_function = self.resolve_module_function(expr.callee)
        if resolved_module_function is not None:
            module_path, function = resolved_module_function
            callee = self.python_function_name(function, module_path=module_path)
        elif len(expr.callee) == 1 and expr.callee[0] in {function.name for function in self.app.functions}:
            function = self.function_by_name(expr.callee[0])
            callee = self.python_function_name(function)
        else:
            callee = "_".join(expr.callee)
        args = ", ".join(self.arg_expr(arg) for arg in expr.args)
        return f"{callee}({args})"

    def arg_expr(self, arg) -> str:
        rendered = self.expr(arg.expr)
        if arg.name is None:
            return rendered
        return f"{arg.name}={rendered}"

    def app_backend(self) -> str:
        backends = {store.backend for store in self.app.stores}
        return next(iter(backends)) if backends else "sqlite"

    def sql_placeholder(self, backend: str | None = None) -> str:
        return "%s" if (backend or self.app_backend()) == "postgres" else "?"

    def sql_type(self, type_ref: TypeRef, *, backend: str | None = None) -> str:
        backend = backend or self.app_backend()
        if backend == "postgres":
            return self.postgres_type(type_ref)
        return self.sqlite_type(type_ref)

    def sqlite_type(self, type_ref: TypeRef) -> str:
        if type_ref.name == "Option" and type_ref.args:
            return self.sqlite_type(type_ref.args[0])
        if type_ref.name == "Bool" or type_ref.name == "Int" or type_ref.name == "Id":
            return "INTEGER"
        if type_ref.name in {"Float", "Money"}:
            return "REAL"
        return "TEXT"

    def postgres_type(self, type_ref: TypeRef) -> str:
        if type_ref.name == "Option" and type_ref.args:
            return self.postgres_type(type_ref.args[0])
        if type_ref.name == "Bool":
            return "BOOLEAN"
        if type_ref.name == "Float":
            return "DOUBLE PRECISION"
        if type_ref.name == "Money":
            return "NUMERIC"
        if type_ref.name == "Int" or type_ref.name == "Id":
            return "INTEGER"
        return "TEXT"

    def sql_identifier(self, name: str) -> str:
        return '"' + name.replace('"', '""') + '"'

    def sqlite_identifier(self, name: str) -> str:
        return self.sql_identifier(name)

    def required_body_fields(self, route: RouteDecl) -> list[str]:
        if route.body_type is None:
            return []
        type_decl = self.type_decl(route.body_type.name)
        return [
            field.name
            for field in type_decl.fields
            if field.name != "id" and field.type_ref.name != "Option"
        ]

    def schema_hash(self) -> str:
        digest = hashlib.sha256()
        for store in self.app.stores:
            type_decl = self.type_decl(store.type_ref.name)
            digest.update(store.name.encode("utf-8"))
            digest.update(store.backend.encode("utf-8"))
            for field in type_decl.fields:
                digest.update(field.name.encode("utf-8"))
                digest.update(field.type_ref.render().encode("utf-8"))
        return digest.hexdigest()

    def resolve_source_path(self, source_path: str, relative_path: str) -> str:
        source = Path(source_path)
        return str((source.parent / relative_path).resolve())

    def type_decl(self, name: str) -> TypeDecl:
        for type_decl in self.app.types:
            if type_decl.name == name:
                return type_decl
        for alias, module in self.app.imported_modules.items():
            for type_decl in module.types:
                if f"{alias}.{type_decl.name}" == name:
                    return type_decl
        raise KeyError(f"Unknown type declaration: {name}")

    def function_by_name(self, name: str) -> FunctionDecl:
        return next(function for function in self.app.functions if function.name == name)

    def python_function_name(self, function: FunctionDecl, *, module_path: tuple[str, ...] = ()) -> str:
        prefix = "cmd" if function.kind == "command" else "fn"
        if module_path:
            return f"{prefix}_{'_'.join(module_path)}_{function.name}"
        return f"{prefix}_{function.name}"

    def enum_variant_literal(self, parts: list[str]) -> str | None:
        if len(parts) == 2:
            enum_name, variant = parts
            if any(enum_decl.name == enum_name and variant in enum_decl.variants for enum_decl in self.app.enums):
                return repr(variant)
            if self.current_module is not None:
                if any(enum_decl.name == enum_name and variant in enum_decl.variants for enum_decl in self.current_module.enums):
                    return repr(variant)
        if len(parts) == 3:
            alias, enum_name, variant = parts
            module = self.resolve_module_alias(alias)
            if module and any(enum_decl.name == enum_name and variant in enum_decl.variants for enum_decl in module.enums):
                return repr(variant)
        return None

    def source_comment(self, location) -> str:
        return f"# source: {location.path}:{location.line}"

    def resolve_module_function(self, callee: list[str]) -> tuple[tuple[str, ...], FunctionDecl] | None:
        if len(callee) == 1 and self.current_module is not None:
            function = self.find_module_function(self.current_module, callee[0])
            if function is not None:
                return self.current_module_path, function
        if len(callee) != 2:
            return None
        alias, name = callee
        module = self.resolve_module_alias(alias)
        if module is None:
            return None
        function = self.find_module_function(module, name)
        if function is None:
            return None
        if self.current_module is not None and alias in self.current_module.imported_modules:
            return (*self.current_module_path, alias), function
        return (alias,), function

    def resolve_module_alias(self, alias: str) -> Module | None:
        if self.current_module is not None and alias in self.current_module.imported_modules:
            return self.current_module.imported_modules[alias]
        return self.app.imported_modules.get(alias)

    def find_module_function(self, module: Module, name: str) -> FunctionDecl | None:
        return next((function for function in module.functions if function.name == name), None)


def build_source_map(code: str, *, generated_path: str) -> dict[str, object]:
    line_map: dict[str, dict[str, object]] = {}
    symbols: dict[str, dict[str, object]] = {}
    current: dict[str, object] | None = None
    primary_source = ""
    for number, line in enumerate(code.splitlines(), start=1):
        stripped = line.strip()
        if not stripped:
            current = None
            continue
        if stripped.startswith("# source: "):
            current = parse_source_comment(stripped)
            if current and not primary_source:
                primary_source = str(current["file"])
        if current is not None:
            line_map[str(number)] = dict(current)
            if stripped.startswith("def "):
                symbol = stripped.split("(", 1)[0].removeprefix("def ").strip()
                symbols[symbol] = dict(current)
    return {
        "version": 1,
        "source": primary_source,
        "generated": generated_path,
        "line_map": line_map,
        "symbols": symbols,
    }


def parse_source_comment(comment: str) -> dict[str, object] | None:
    raw = comment.removeprefix("# source: ").strip()
    try:
        path, line = raw.rsplit(":", 1)
        return {"file": path, "line": int(line), "column": 1, "symbol": ""}
    except ValueError:
        return None
