from __future__ import annotations

import json
from dataclasses import dataclass

from symboliclight.ast import (
    App,
    AssertStmt,
    BinaryExpr,
    CallExpr,
    Expr,
    FunctionDecl,
    IfStmt,
    LetStmt,
    ListExpr,
    LiteralExpr,
    Module,
    PathExpr,
    RecordExpr,
    ReturnStmt,
    RouteDecl,
    Stmt,
    TypeDecl,
    TypeRef,
)


def generate_python(app: App) -> str:
    if not isinstance(app, App):
        raise TypeError("Only app files can be compiled to Python.")
    generator = PythonGenerator(app)
    return generator.generate()


@dataclass(slots=True)
class PythonGenerator:
    app: App
    current_module_path: tuple[str, ...] = ()
    current_module: Module | None = None

    def generate(self) -> str:
        lines: list[str] = [
            "# Generated by SymbolicLight. Do not edit by hand.",
            "from __future__ import annotations",
            "",
            "import argparse",
            "import json",
            "import os",
            "import sqlite3",
            "from http.server import BaseHTTPRequestHandler, HTTPServer",
            "",
            "CONN = None",
            "",
            "def connect(db_path=None):",
            "    global CONN",
            "    path = db_path or os.environ.get('SL_DB', 'symboliclight.sqlite')",
            "    CONN = sqlite3.connect(path)",
            "    CONN.row_factory = sqlite3.Row",
            "    init_db()",
            "    return CONN",
            "",
            "def conn():",
            "    return CONN or connect()",
            "",
            "def json_ready(value):",
            "    return value",
            "",
            "def print_json(value):",
            "    print(json.dumps(json_ready(value), ensure_ascii=False, indent=2))",
            "",
            "def some(value):",
            "    return value",
            "",
            "def none():",
            "    return None",
            "",
            "def ok(value):",
            "    return {'ok': value}",
            "",
            "def err(value):",
            "    return {'err': value}",
            "",
        ]
        lines.extend(self.emit_init_db())
        lines.extend(self.emit_imported_functions())
        for function in self.app.functions:
            lines.extend(self.emit_function(function))
        for route in self.app.routes:
            lines.extend(self.emit_route(route))
        lines.extend(self.emit_server())
        lines.extend(self.emit_tests())
        lines.extend(self.emit_main())
        return "\n".join(lines) + "\n"

    def emit_init_db(self) -> list[str]:
        lines = ["def init_db():", "    database = conn()"]
        if not self.app.stores:
            lines.append("    return")
        for store in self.app.stores:
            type_decl = self.type_decl(store.type_ref.name)
            columns = []
            for field in type_decl.fields:
                if field.name == "id":
                    columns.append("id INTEGER PRIMARY KEY AUTOINCREMENT")
                else:
                    columns.append(f"{field.name} {self.sqlite_type(field.type_ref)}")
            sql = f"CREATE TABLE IF NOT EXISTS {store.name} ({', '.join(columns)})"
            lines.append(f"    database.execute({sql!r})")
        lines.extend(["    database.commit()", ""])
        for store in self.app.stores:
            lines.extend(self.emit_store_helpers(store.name, self.type_decl(store.type_ref.name)))
        return lines

    def emit_store_helpers(self, store_name: str, type_decl: TypeDecl) -> list[str]:
        data_fields = [field for field in type_decl.fields if field.name != "id"]
        columns = ", ".join(field.name for field in data_fields)
        placeholders = ", ".join("?" for _ in data_fields)
        values = ", ".join(f"item.get({field.name!r})" for field in data_fields)
        lines = [
            f"def {store_name}_normalize(item):",
            "    item = dict(item)",
        ]
        bool_fields = [field.name for field in type_decl.fields if field.type_ref.name == "Bool"]
        if bool_fields:
            for field_name in bool_fields:
                lines.append(f"    if {field_name!r} in item:")
                lines.append(f"        item[{field_name!r}] = bool(item[{field_name!r}])")
        lines.extend(
            [
                "    return item",
                "",
            ]
        )
        lines.extend([
            f"def {store_name}_insert(item):",
            f"    cursor = conn().execute('INSERT INTO {store_name} ({columns}) VALUES ({placeholders})', [{values}])",
            "    conn().commit()",
            f"    return {store_name}_get(cursor.lastrowid)",
            "",
            f"def {store_name}_all():",
            f"    rows = conn().execute('SELECT * FROM {store_name} ORDER BY id').fetchall()",
            f"    return [{store_name}_normalize(dict(row)) for row in rows]",
            "",
            f"def {store_name}_get(item_id):",
            f"    row = conn().execute('SELECT * FROM {store_name} WHERE id = ?', [item_id]).fetchone()",
            f"    return {store_name}_normalize(dict(row)) if row else None",
            "",
            f"def {store_name}_update(item_id, item):",
            "    item = dict(item)",
            f"    conn().execute('UPDATE {store_name} SET {', '.join(field.name + ' = ?' for field in data_fields)} WHERE id = ?', [{values}, item_id])",
            "    conn().commit()",
            f"    return {store_name}_get(item_id)",
            "",
            f"def {store_name}_delete(item_id):",
            f"    cursor = conn().execute('DELETE FROM {store_name} WHERE id = ?', [item_id])",
            "    conn().commit()",
            "    return cursor.rowcount > 0",
            "",
            f"def {store_name}_filter(**criteria):",
            f"    allowed = {sorted(field.name for field in type_decl.fields)!r}",
            "    for key in criteria:",
            "        if key not in allowed:",
            "            raise ValueError(f'unknown filter field: {key}')",
            "    if not criteria:",
            f"        return {store_name}_all()",
            "    where = ' AND '.join(f'{key} = ?' for key in criteria)",
            f"    rows = conn().execute('SELECT * FROM {store_name} WHERE ' + where + ' ORDER BY id', list(criteria.values())).fetchall()",
            f"    return [{store_name}_normalize(dict(row)) for row in rows]",
            "",
        ])
        return lines

    def emit_imported_functions(self) -> list[str]:
        lines: list[str] = []
        for alias, module in self.app.imported_modules.items():
            lines.extend(self.emit_module_functions((alias,), module))
        return lines

    def emit_module_functions(self, module_path: tuple[str, ...], module: Module) -> list[str]:
        lines: list[str] = []
        for alias, imported in module.imported_modules.items():
            lines.extend(self.emit_module_functions((*module_path, alias), imported))
        for function in module.functions:
            lines.extend(self.emit_function(function, module_path=module_path, module=module))
        return lines

    def emit_function(
        self,
        function: FunctionDecl,
        *,
        module_path: tuple[str, ...] = (),
        module: Module | None = None,
    ) -> list[str]:
        name = self.python_function_name(function, module_path=module_path)
        params = ", ".join(param.name for param in function.params)
        lines = [self.source_comment(function.location), f"def {name}({params}):"]
        previous_module_path = self.current_module_path
        previous_module = self.current_module
        self.current_module_path = module_path
        self.current_module = module
        lines.extend(self.emit_body(function.body, indent="    "))
        self.current_module_path = previous_module_path
        self.current_module = previous_module
        if not function.body:
            lines.append("    pass")
        lines.append("")
        return lines

    def emit_route(self, route: RouteDecl) -> list[str]:
        lines = [self.source_comment(route.location), f"def {route.function_name}(request):"]
        lines.extend(self.emit_body(route.body, indent="    "))
        lines.append("")
        return lines

    def emit_body(self, statements: list[Stmt], *, indent: str) -> list[str]:
        lines: list[str] = []
        for stmt in statements:
            if isinstance(stmt, LetStmt):
                lines.append(f"{indent}{stmt.name} = {self.expr(stmt.expr)}")
            elif isinstance(stmt, ReturnStmt):
                lines.append(f"{indent}return {self.expr(stmt.expr)}")
            elif isinstance(stmt, AssertStmt):
                lines.append(f"{indent}assert {self.expr(stmt.expr)}")
            elif isinstance(stmt, IfStmt):
                lines.append(f"{indent}if {self.expr(stmt.condition)}:")
                lines.extend(self.emit_body(stmt.then_body, indent=indent + "    ") or [indent + "    pass"])
                if stmt.else_body:
                    lines.append(f"{indent}else:")
                    lines.extend(self.emit_body(stmt.else_body, indent=indent + "    "))
            else:
                lines.append(f"{indent}{self.expr(stmt.expr)}")
        return lines

    def emit_server(self) -> list[str]:
        route_entries = []
        for route in self.app.routes:
            route_entries.append(f"    ({route.method!r}, {route.path!r}): {route.function_name},")
        return [
            "ROUTES = {",
            *route_entries,
            "}",
            "",
            "class Request:",
            "    def __init__(self, body=None):",
            "        self.body = body or {}",
            "",
            "class Handler(BaseHTTPRequestHandler):",
            "    def do_GET(self):",
            "        self.handle_method('GET')",
            "",
            "    def do_POST(self):",
            "        self.handle_method('POST')",
            "",
            "    def do_PUT(self):",
            "        self.handle_method('PUT')",
            "",
            "    def do_PATCH(self):",
            "        self.handle_method('PATCH')",
            "",
            "    def do_DELETE(self):",
            "        self.handle_method('DELETE')",
            "",
            "    def handle_method(self, method):",
            "        handler = ROUTES.get((method, self.path))",
            "        if handler is None:",
            "            self.send_response(404)",
            "            self.end_headers()",
            "            self.wfile.write(b'not found')",
            "            return",
            "        length = int(self.headers.get('Content-Length', '0'))",
            "        raw = self.rfile.read(length).decode('utf-8') if length else '{}'",
            "        body = json.loads(raw or '{}')",
            "        result = handler(Request(body))",
            "        payload = json.dumps(result, ensure_ascii=False).encode('utf-8')",
            "        self.send_response(200)",
            "        self.send_header('Content-Type', 'application/json; charset=utf-8')",
            "        self.send_header('Content-Length', str(len(payload)))",
            "        self.end_headers()",
            "        self.wfile.write(payload)",
            "",
            "def serve(host='127.0.0.1', port=8000):",
            "    connect()",
            "    server = HTTPServer((host, port), Handler)",
            "    print(f'SymbolicLight app serving on http://{host}:{port}')",
            "    server.serve_forever()",
            "",
        ]

    def emit_tests(self) -> list[str]:
        lines = ["def run_tests():", "    connect(':memory:')"]
        if not self.app.tests:
            lines.append("    print('No tests defined.')")
            return lines + [""]
        executable_tests = 0
        for test in self.app.tests:
            lines.append(f"    {self.source_comment(test.location).lstrip()}")
            if test.external_ref is not None:
                lines.append(f"    print('skipped external test: {test.external_ref}')")
                continue
            executable_tests += 1
            lines.append(f"    # {test.name}")
            lines.extend(self.emit_body(test.body, indent="    "))
        lines.append(f"    print('ok - {executable_tests} test(s) passed')")
        lines.append("")
        return lines

    def emit_main(self) -> list[str]:
        lines = [
            "def main(argv=None):",
            "    parser = argparse.ArgumentParser(prog='sl-app')",
            "    sub = parser.add_subparsers(dest='command', required=True)",
            "    serve_parser = sub.add_parser('serve')",
            "    serve_parser.add_argument('--host', default='127.0.0.1')",
            "    serve_parser.add_argument('--port', type=int, default=8000)",
            "    sub.add_parser('test')",
        ]
        for function in self.app.functions:
            if function.kind != "command":
                continue
            lines.append(f"    {function.name}_parser = sub.add_parser({function.name!r})")
            for param in function.params:
                if param.type_ref.name == "Bool":
                    lines.append(f"    {function.name}_parser.add_argument('--{param.name}', action='store_true')")
                elif param.type_ref.name == "Int":
                    lines.append(f"    {function.name}_parser.add_argument({param.name!r}, type=int)")
                elif param.type_ref.name == "Float":
                    lines.append(f"    {function.name}_parser.add_argument({param.name!r}, type=float)")
                else:
                    lines.append(f"    {function.name}_parser.add_argument({param.name!r})")
        lines.extend(
            [
                "    args = parser.parse_args(argv)",
                "    if args.command == 'serve':",
                "        serve(args.host, args.port)",
                "        return",
                "    if args.command == 'test':",
                "        run_tests()",
                "        return",
                "    connect()",
            ]
        )
        for function in self.app.functions:
            if function.kind != "command":
                continue
            params = ", ".join(f"args.{param.name}" for param in function.params)
            lines.extend(
                [
                    f"    if args.command == {function.name!r}:",
                    f"        print_json({self.python_function_name(function)}({params}))",
                    "        return",
                ]
            )
        lines.extend(["", "if __name__ == '__main__':", "    main()", ""])
        return lines

    def expr(self, expr: Expr) -> str:
        if isinstance(expr, LiteralExpr):
            return repr(expr.value)
        if isinstance(expr, PathExpr):
            return self.path_expr(expr.parts)
        if isinstance(expr, RecordExpr):
            fields = ", ".join(f"{field.name!r}: {self.expr(field.expr)}" for field in expr.fields)
            return "{" + fields + "}"
        if isinstance(expr, ListExpr):
            return "[" + ", ".join(self.expr(item) for item in expr.items) + "]"
        if isinstance(expr, BinaryExpr):
            op = {"&&": "and", "||": "or"}.get(expr.op, expr.op)
            return f"({self.expr(expr.left)} {op} {self.expr(expr.right)})"
        if isinstance(expr, CallExpr):
            return self.call_expr(expr)
        raise TypeError(f"Unsupported expression: {expr!r}")

    def path_expr(self, parts: list[str]) -> str:
        enum_literal = self.enum_variant_literal(parts)
        if enum_literal is not None:
            return enum_literal
        if parts[:2] == ["request", "body"] and len(parts) == 3:
            return f"request.body.get({parts[2]!r})"
        if len(parts) == 2:
            return f"{parts[0]}.get({parts[1]!r})"
        return parts[0]

    def call_expr(self, expr: CallExpr) -> str:
        if len(expr.callee) == 2 and expr.callee[0] in {store.name for store in self.app.stores}:
            store, method = expr.callee
            args = ", ".join(self.arg_expr(arg) for arg in expr.args)
            return f"{store}_{method}({args})"
        resolved_module_function = self.resolve_module_function(expr.callee)
        if resolved_module_function is not None:
            module_path, function = resolved_module_function
            callee = self.python_function_name(function, module_path=module_path)
        elif len(expr.callee) == 1 and expr.callee[0] in {function.name for function in self.app.functions}:
            function = self.function_by_name(expr.callee[0])
            callee = self.python_function_name(function)
        else:
            callee = "_".join(expr.callee)
        args = ", ".join(self.arg_expr(arg) for arg in expr.args)
        return f"{callee}({args})"

    def arg_expr(self, arg) -> str:
        rendered = self.expr(arg.expr)
        if arg.name is None:
            return rendered
        return f"{arg.name}={rendered}"

    def sqlite_type(self, type_ref: TypeRef) -> str:
        if type_ref.name == "Option" and type_ref.args:
            return self.sqlite_type(type_ref.args[0])
        if type_ref.name == "Bool" or type_ref.name == "Int" or type_ref.name == "Id":
            return "INTEGER"
        if type_ref.name == "Float":
            return "REAL"
        return "TEXT"

    def type_decl(self, name: str) -> TypeDecl:
        for type_decl in self.app.types:
            if type_decl.name == name:
                return type_decl
        for alias, module in self.app.imported_modules.items():
            for type_decl in module.types:
                if f"{alias}.{type_decl.name}" == name:
                    return type_decl
        raise KeyError(f"Unknown type declaration: {name}")

    def function_by_name(self, name: str) -> FunctionDecl:
        return next(function for function in self.app.functions if function.name == name)

    def python_function_name(self, function: FunctionDecl, *, module_path: tuple[str, ...] = ()) -> str:
        prefix = "cmd" if function.kind == "command" else "fn"
        if module_path:
            return f"{prefix}_{'_'.join(module_path)}_{function.name}"
        return f"{prefix}_{function.name}"

    def enum_variant_literal(self, parts: list[str]) -> str | None:
        if len(parts) == 2:
            enum_name, variant = parts
            if any(enum_decl.name == enum_name and variant in enum_decl.variants for enum_decl in self.app.enums):
                return repr(variant)
            if self.current_module is not None:
                if any(enum_decl.name == enum_name and variant in enum_decl.variants for enum_decl in self.current_module.enums):
                    return repr(variant)
        if len(parts) == 3:
            alias, enum_name, variant = parts
            module = self.resolve_module_alias(alias)
            if module and any(enum_decl.name == enum_name and variant in enum_decl.variants for enum_decl in module.enums):
                return repr(variant)
        return None

    def source_comment(self, location) -> str:
        return f"# source: {location.path}:{location.line}"

    def resolve_module_function(self, callee: list[str]) -> tuple[tuple[str, ...], FunctionDecl] | None:
        if len(callee) == 1 and self.current_module is not None:
            function = self.find_module_function(self.current_module, callee[0])
            if function is not None:
                return self.current_module_path, function
        if len(callee) != 2:
            return None
        alias, name = callee
        module = self.resolve_module_alias(alias)
        if module is None:
            return None
        function = self.find_module_function(module, name)
        if function is None:
            return None
        if self.current_module is not None and alias in self.current_module.imported_modules:
            return (*self.current_module_path, alias), function
        return (alias,), function

    def resolve_module_alias(self, alias: str) -> Module | None:
        if self.current_module is not None and alias in self.current_module.imported_modules:
            return self.current_module.imported_modules[alias]
        return self.app.imported_modules.get(alias)

    def find_module_function(self, module: Module, name: str) -> FunctionDecl | None:
        return next((function for function in module.functions if function.name == name), None)
